### ISSUE TITLE
Alguns pontos a destacar

### ISSUE THREAD

**Issue by Vmarcelo49** [GustavoFerrari7/UminekoScriptPort#1]
De acordo com o rapaz que fez a tradução, o numero de linhas não é o mesmo entre as versões, e as proprias linhas não são iguais em alguns lugares especificos.

se quiser ser o brabo mesmo seria legal adaptar a tradução pra esse projeto https://github.com/DCNick3/shin a versão steam tem muitas incoveniencias pra valer apena portar

**Comment by GustavoFerrari7** [comment]
Sim, eu vi que é diferente tanto em número de linhas quanto em conteúdo de várias delas, por isso q o programa não é 100% automático e eu tenho que fazer bastante coisa manual, e até mesmo adaptar a tradução da Knox.

E se minha vontade realmente me levar a traduzir/portar o jogo inteiro, eu vou fazer o da Steam, primeiro pq é em cima do 07th-mod que to fazendo e ele deixa o jogo mais parecido com as outras versões, mesmo ainda tendo limitações da engine, eu não acho que seja um problema. 

E segundo pq só tenho interesse de fazer pra Steam mesmo por comodismo mesmo, qualquer outra eu não ia nem me dar ao trabalho de pensar em fazer algo
